# Generated by Django 5.2 on 2025-04-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vps_app", "0002_service_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["id"]},
        ),
    ]
