# Generated by Django 5.2 on 2025-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps_app", "0003_alter_service_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
